# Generated by Django 5.1.4 on 2025-01-01 17:01

import django.db.models.deletion
import shortuuid.main
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256, primary_key=True, serialize=False)),
                ('share_link', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256)),
                ('title', models.CharField(help_text='This is name of your maturity assessment and shown to users when they fill in your assessment survey.', max_length=1024, verbose_name='Survey title')),
                ('email', models.EmailField(max_length=254)),
                ('organisation', models.CharField(help_text='The name of your organisation. We collect this to let users know they are responding to the correct survey.', max_length=2048)),
                ('preamble', models.TextField(blank=True, help_text='This is a rich-text field you can text is shown to respondents on the first page of the assessment survey.', verbose_name='Introductory text')),
                ('confirmation_message', models.TextField(blank=True, help_text='This is a rich-text field shown to respondents after they have completed their survey.')),
                ('qualitative', models.PositiveIntegerField(choices=[(1, 'Show free-text qualitative options'), (2, 'Hide free-text qualitative options')], default=1, help_text="If selected, we will ask additional questions for each of the 'I-D-E-A-L' behaviours that can be downloaded and analysed.", verbose_name='Include qualitative questions')),
                ('industry', models.CharField(choices=[('A', 'Agriculture, forestry and fishing'), ('B', 'Mining and quarrying'), ('C', 'Manufacturing'), ('D', 'Electricity, gas, steam and air conditioning supply'), ('E', 'Water supply; sewerage, waste management and remediation activities'), ('F', 'Construction'), ('G', 'Wholesale and retail trade; repair of motor vehicles and motorcycles'), ('H', 'Transportation and storage'), ('I', 'Accommodation and food service activities'), ('J', 'Information and communication'), ('K', 'Financial and insurance activities'), ('L', 'Real estate activities'), ('M', 'Professional, scientific and technical activities'), ('N', 'Administrative and support service activities'), ('O', 'Public administration and defence; compulsory social security'), ('P', 'Education'), ('Q', 'Human health and social work activities'), ('R', 'Arts, entertainment and recreation'), ('S', 'Other service activities'), ('T', 'Activities of households as employers; undifferentiated goods- and services-producing activities of households for own use'), ('U', 'Activities of extraterritorial organizations and bodies')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2048)),
                ('close_date', models.DateField(help_text='When do you want to stop recieving responses? Leave blank to keep the phase open indefinitely.', null=True)),
                ('expected_responses', models.PositiveIntegerField(help_text='What is the expected number of responses you expect to get in this phase?')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=2048)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='mast_toolkit.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('beliefs_metadata_1', models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Don't Know")], default=None, max_length=2, verbose_name='My organisation understands how data documentation supports the delivery of core functions and outcomes.')),
                ('beliefs_analysis_1', models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Don't Know")], default=None, max_length=2, verbose_name='My organisation documents why data is collected, along with what is stored.')),
                ('beliefs_standards_1', models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Don't Know")], default=None, max_length=2, verbose_name='My organisation has a consistent approach to data documentation.')),
                ('beliefs_teamwork_1', models.PositiveIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Don't Know")], default=None, max_length=2, verbose_name='Teams in my organisation are encouraged to create, review and share documentation for their data assets.')),
                ('actions_inventory_1', models.PositiveIntegerField(choices=[(1, "I don't do this as part of my current role"), (2, 'I do not have access to a central data discovery location'), (3, 'My team has a list of data assets, but I am not aware of data outside my team'), (4, 'I have access to a list of data assets that is shared by members of my organisation'), (5, 'I have restricted access to metadata within a central data inventory based on my needs and permissions')], default=None, verbose_name='Where do you go to discover other data assets in the organisation?')),
                ('actions_inventory_2', models.PositiveIntegerField(choices=[(1, "I don't do this as part of my current role"), (2, 'I do not have a tool for recording documentation about data assets made within my team'), (3, 'I use ad hoc systems like Excel or Word etc.'), (4, 'I use generalised documentation systems such as SharePoint or Confluence'), (5, 'I use specialised data cataloguing tools for documenting data assets')], default=None, verbose_name=' How do you record the existence of data assets within your team?')),
                ('actions_inventory_qual', models.TextField(blank=True, verbose_name="(Optional) Please include a list of processes, systems or tools you use to find data in your organisation. If this includes emailing people you know, you can just include 'email' as one of your processes.")),
                ('actions_document_1', models.PositiveIntegerField(choices=[(1, "I don't do this as part of my current role"), (2, 'I do not document data assets at this point in time'), (3, 'I document data based on my own needs or requirements'), (4, 'My team has its own processes for documenting data'), (5, 'I use organisational standards for recording information about data assets')], default=None, verbose_name='What information do you record for data assets created within your team?')),
                ('actions_document_2', models.PositiveIntegerField(choices=[(1, "I don't do this as part of my current role"), (2, 'I do not record information at this level about our data'), (3, 'I record the names and descriptions of columns'), (4, 'I record the names, descriptions, and any codes or data types for each column'), (5, 'I record the names, descriptions and codes for each column, and include links to common data glossary defintions')], default=None, verbose_name='What information do you or your team record about fields within a data asset, such as describing columns in a spreadsheet or database table?')),
                ('actions_document_qual', models.TextField(blank=True, verbose_name='(Optional) Please include a list of systems or tools you use to document data in your organisation. If this includes tools like Word, Excel, Sharepoint or other similar knowledge management tools, include these as tools you use.')),
                ('actions_endorse_1', models.PositiveIntegerField(choices=[(1, "I don't do this as part of my current role"), (2, 'Data documentation does not get reviewed at this point in time'), (3, 'Data documentation is reviewed on an informal basis by my peers'), (4, 'My team has a process for reviewing data documentation'), (5, 'Data governance team(s) within the organisation review data documentation')], default=None, verbose_name='Who is responsible for reviewing data documentation in your team or organisation?')),
                ('actions_endorse_2', models.PositiveIntegerField(choices=[(1, "I don't do this as part of my current role"), (2, 'I do not have access to documentation from other teams'), (3, 'I can view information about data assets, but am unable to see approval documentation'), (4, 'I can view approval processes for data documentation within my team'), (5, 'Approval processes are documented in a formal register in the organisation')], default=None, verbose_name='How can you find out who has signed off on approval/review of data assets in the organisation?')),
                ('actions_endorse_qual', models.TextField(blank=True, verbose_name='(Optional) Please tell us about business areas you engage with to assist with publication of data documentation, and any internal or external stakeholders who you think would find your data documentation useful.')),
                ('actions_audit_1', models.PositiveIntegerField(choices=[(1, "I don't do this as part of my current role"), (2, 'I do not manage common data terms at this point in time'), (3, 'I use methods such as copying and pasting existing definitions from existing records for consistency when documenting new data assets'), (4, 'My team has a list of data terms that we manage internally'), (5, 'My team manages our data terms in a governed central system that records and links these terms to data assets')], default=None, verbose_name='How do you or your team manage common data terms?')),
                ('actions_audit_2', models.PositiveIntegerField(choices=[(1, "I don't do this as part of my current role"), (2, 'I do not use a data glossary as part of my work '), (3, 'I use methods such as copying and pasting definitions from a data glossary'), (4, 'I copy and paste definitions and include a link to the source, such as a document or data glossary web page'), (5, 'I reference glossary terms from a central source that provides links between data assets and data terms')], default=None, verbose_name='How do you reuse common data terms from a data glossary?')),
                ('actions_audit_qual', models.TextField(blank=True, verbose_name='(Optional) Please tell us about terms you use commonly in your work that may not be understood by users of your data, or may not be used the same way as another team. Examples could include terms like supplier, staff member or identifier.')),
                ('actions_leadership_1', models.PositiveIntegerField(choices=[(1, 'I do not manage data in my role, and am not impacted by data policies'), (2, 'I am not aware of policies for managing data assets at the present time'), (3, 'My team has internal policies for managing data assets'), (4, 'I am aware of policies for managing data assets, but am not aware of how they relate to my role'), (5, "I am aware of our organisation's data governance and data management policies, and how I am responsible for data safety")], default=None, verbose_name='Are you aware of policies for managing data assets within your team or organisation?')),
                ('actions_leadership_2', models.PositiveIntegerField(choices=[(1, 'I do not use metadata in my role'), (2, 'I am not aware of metadata promotion within the organisation at the present time'), (3, 'Metadata is promoted within my team but not at an organisational level'), (4, 'Metadata is promoted internally e.g. through the organisation’s intranet'), (5, 'Metadata is promoted both internally and externally, e.g. in the annual report or on our website')], default=None, verbose_name="How does your organisation's leadership promote metadata adoption?")),
                ('actions_leadership_qual', models.TextField(blank=True, verbose_name='(Optional) Please tell us about policies around data use and access that impact you in your role.')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='mast_toolkit.businessunit')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='mast_toolkit.survey')),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='mast_toolkit.wave')),
            ],
        ),
    ]
