# Generated by Django 5.1.4 on 2025-08-01 11:03

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast_toolkit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='confirmation_message',
            field=models.TextField(blank=True, help_text='This is a closing paragraph shown to respondents after they have completed their survey.'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='include_data_used_or_created',
            field=models.PositiveIntegerField(choices=[(1, 'Show question on data used and created by the respondent'), (2, 'Hide question on data used and created by the respondent')], default=2, help_text="If selected, we will ask additional questions for each of the 'I-D-E-A-L' behaviours that can be downloaded and analysed.", verbose_name='Ask respondents about data they use'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='preamble',
            field=models.TextField(blank=True, help_text='This is a closing paragraph that is shown to respondents at the start of the assessment survey.', verbose_name='Introductory text'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='share_link',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256),
        ),
    ]
