# Generated by Django 5.1.4 on 2026-03-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mast_toolkit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "Accommodation and food service activities"),
                    ("N", "Administrative and support service activities"),
                    ("A", "Agriculture, forestry and fishing"),
                    ("R", "Arts, entertainment and recreation"),
                    ("F", "Construction"),
                    ("P", "Education"),
                    ("D", "Electricity, gas, steam and air conditioning supply"),
                    ("K", "Financial and insurance activities"),
                    ("Q", "Human health and social work activities"),
                    ("J", "Information and communication"),
                    ("C", "Manufacturing"),
                    ("L", "Real estate activities"),
                    ("B", "Mining and quarrying"),
                    ("M", "Professional, scientific and technical activities"),
                    (
                        "O",
                        "Public administration and defence; compulsory social security",
                    ),
                    ("H", "Transportation and storage"),
                    (
                        "E",
                        "Water supply; sewerage, waste management and remediation activities",
                    ),
                    (
                        "G",
                        "Wholesale and retail trade; repair of motor vehicles and motorcycles",
                    ),
                    ("S", "Other service activities"),
                ],
                max_length=1,
                null=True,
                verbose_name="Industry",
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="response",
            name="seniority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C", "CXO / Executive (15+ years)"),
                    ("S", "Senior (8–15 years)"),
                    ("M", "Mid-Level (3–7 years)"),
                    ("J", "Junior (0–2 years)"),
                ],
                max_length=1,
                null=True,
                verbose_name="Seniority level",
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="tools",
            field=models.TextField(
                blank=True,
                verbose_name="What tools do you use to document and organise data at your organisation?",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="benchmark_scope",
            field=models.PositiveIntegerField(
                choices=[(1, "Organisation-Only"), (2, "Industry-Wide")],
                default=1,
                help_text="Select whether to compare results within your organisation only or across the industry.",
                verbose_name="Survey type",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="actions_audit_1",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "I don't do this as part of my current role"),
                    (2, "I do not manage common data terms at this point in time"),
                    (
                        3,
                        "I use methods such as copying and pasting existing definitions from existing records for consistency when documenting new data assets",
                    ),
                    (
                        4,
                        "I refer to a list of data terms that my team manages internally",
                    ),
                    (
                        5,
                        "I use data terms from a governed central system that records and links these terms to data assets",
                    ),
                ],
                default=None,
                null=True,
                verbose_name="How do you manage commonly referenced data terms?",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="actions_audit_2",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "I don't do this as part of my current role"),
                    (2, "I do not use a data glossary as part of my work "),
                    (
                        3,
                        "I use methods such as copying and pasting definitions from a data glossary",
                    ),
                    (
                        4,
                        "I copy and paste definitions and include a link to the source, such as a document or data glossary web page",
                    ),
                    (
                        5,
                        "I reference glossary terms from a central source that provides links between data assets and data terms",
                    ),
                ],
                default=None,
                null=True,
                verbose_name="How do you reuse common data terms from a data glossary?",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="actions_document_1",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "I don't do this as part of my current role"),
                    (2, "I do not document data assets at this point in time"),
                    (3, "I document data based on my own needs or requirements"),
                    (
                        4,
                        "I follow processes my team has developed for documenting data",
                    ),
                    (
                        5,
                        "I follow organisational standards for recording information about data assets",
                    ),
                ],
                default=None,
                help_text="If more than one is applicable, select the activity you most commonly perform.",
                null=True,
                verbose_name="What information do you usually record for data assets created within your team?",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="actions_document_2",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "I don't do this as part of my current role"),
                    (2, "I do not record information at this level about our data"),
                    (3, "I record the names and descriptions of columns"),
                    (
                        4,
                        "I record the names, descriptions, and any codes or data types for each column",
                    ),
                    (
                        5,
                        "I record the names, descriptions and codes for each column, and include links to common data glossary defintions",
                    ),
                ],
                default=None,
                help_text="If more than one is applicable, select the activity you most commonly perform.",
                null=True,
                verbose_name="What information do you or your team commonly record about fields within a data asset, such as describing columns in a spreadsheet or database table?",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="actions_endorse_1",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "I don't do this as part of my current role"),
                    (
                        2,
                        "Data documentation does not get reviewed at this point in time",
                    ),
                    (
                        3,
                        "Data documentation is reviewed on an informal basis by my peers",
                    ),
                    (4, "My team has a process for reviewing data documentation"),
                    (
                        5,
                        "Data governance team(s) within the organisation review data documentation",
                    ),
                ],
                default=None,
                help_text="If more than one is applicable, select the answer that matches you usual routine.",
                null=True,
                verbose_name="Who is responsible for reviewing data documentation in your team or organisation?",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="actions_endorse_2",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "I don't do this as part of my current role"),
                    (2, "I do not have access to documentation from other teams"),
                    (
                        3,
                        "I can view information about data assets, but am unable to see approval documentation",
                    ),
                    (
                        4,
                        "I can view approval processes for data documentation within my team",
                    ),
                    (
                        5,
                        "Approval processes for all data I use is documented in a formal register in the organisation",
                    ),
                ],
                default=None,
                null=True,
                verbose_name="How can you find out who has signed off on approval/review of data assets in the organisation?",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="actions_inventory_1",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "I don't do this as part of my current role"),
                    (
                        2,
                        "I will speak directly to a person who I think knows about this data",
                    ),
                    (
                        3,
                        "I have access to a list of data assets managed by my team, but I am not aware of data outside my team",
                    ),
                    (
                        4,
                        "I have access to a list of data assets that is shared by members of my organisation",
                    ),
                    (
                        5,
                        "I can search for data within a central data inventory that returns results based on my needs and permissions",
                    ),
                ],
                default=None,
                help_text="If more than one is applicable, select the activity you most commonly perform.",
                null=True,
                verbose_name="How do you most commonly discover other data assets in the organisation?",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="actions_inventory_2",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "I don't do this as part of my current role"),
                    (
                        2,
                        "I do not have a tool for recording documentation about data assets made within my team",
                    ),
                    (3, "I use ad hoc systems like Excel or Word etc."),
                    (
                        4,
                        "I use generalised documentation systems such as SharePoint or Confluence",
                    ),
                    (
                        5,
                        "I use specialised data cataloguing tools for documenting data assets",
                    ),
                ],
                default=None,
                help_text="If more than one is applicable, select the activity you most commonly perform.",
                null=True,
                verbose_name="How do you most commonly record the existence of data assets within your team?",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="actions_leadership_1",
            field=models.PositiveIntegerField(
                choices=[
                    (
                        1,
                        "I do not manage data in my role, and am not impacted by data policies",
                    ),
                    (
                        2,
                        "I am not aware of policies for managing data assets at the present time",
                    ),
                    (
                        3,
                        "I am aware of internal policies my team has developed for managing data assets",
                    ),
                    (
                        4,
                        "I am aware of policies for managing data assets, but am not aware of how they relate to my role",
                    ),
                    (
                        5,
                        "I am aware of our organisation's data governance and data management policies, and my responsiblity for data safety",
                    ),
                ],
                default=None,
                null=True,
                verbose_name="Are you aware of policies for managing data assets within your organisation?",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="actions_leadership_2",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "I do not use metadata in my role"),
                    (
                        2,
                        "I am not aware of metadata promotion within the organisation at the present time",
                    ),
                    (
                        3,
                        "Metadata is promoted within my team but not at an organisational level",
                    ),
                    (
                        4,
                        "Metadata is promoted internally e.g. through the organisation’s intranet",
                    ),
                    (
                        5,
                        "Metadata is promoted both internally and externally, e.g. in the annual report or on our website",
                    ),
                ],
                default=None,
                null=True,
                verbose_name="How does your organisation's leadership promote metadata adoption?",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="beliefs_analysis_1",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Strongly Disagree"),
                    (2, "Disagree"),
                    (3, "Neither Agree nor Disagree"),
                    (4, "Agree"),
                    (5, "Strongly Agree"),
                    (9, "Don't Know"),
                ],
                default=None,
                null=True,
                verbose_name="My organisation documents why data is collected, along with what is stored.",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="beliefs_analysis_2",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Strongly Disagree"),
                    (2, "Disagree"),
                    (3, "Neither Agree nor Disagree"),
                    (4, "Agree"),
                    (5, "Strongly Agree"),
                    (9, "Don't Know"),
                ],
                default=None,
                null=True,
                verbose_name="It is easy for me to find documentation that describes what data means.",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="beliefs_metadata_1",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Strongly Disagree"),
                    (2, "Disagree"),
                    (3, "Neither Agree nor Disagree"),
                    (4, "Agree"),
                    (5, "Strongly Agree"),
                    (9, "Don't Know"),
                ],
                default=None,
                null=True,
                verbose_name="My organisation understands how data documentation supports the delivery of core functions and outcomes.",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="beliefs_metadata_2",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Strongly Disagree"),
                    (2, "Disagree"),
                    (3, "Neither Agree nor Disagree"),
                    (4, "Agree"),
                    (5, "Strongly Agree"),
                    (9, "Don't Know"),
                ],
                default=None,
                null=True,
                verbose_name="It is easy for me to find data I need for my role.",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="beliefs_standards_1",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Strongly Disagree"),
                    (2, "Disagree"),
                    (3, "Neither Agree nor Disagree"),
                    (4, "Agree"),
                    (5, "Strongly Agree"),
                    (9, "Don't Know"),
                ],
                default=None,
                null=True,
                verbose_name="My organisation has a consistent approach to data documentation.",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="beliefs_standards_2",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Strongly Disagree"),
                    (2, "Disagree"),
                    (3, "Neither Agree nor Disagree"),
                    (4, "Agree"),
                    (5, "Strongly Agree"),
                    (9, "Don't Know"),
                ],
                default=None,
                null=True,
                verbose_name="It is easy for me to find, link and compare related data using common terms.",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="beliefs_teamwork_1",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Strongly Disagree"),
                    (2, "Disagree"),
                    (3, "Neither Agree nor Disagree"),
                    (4, "Agree"),
                    (5, "Strongly Agree"),
                    (9, "Don't Know"),
                ],
                default=None,
                null=True,
                verbose_name="Teams in my organisation are encouraged to create, review and share documentation for their data assets.",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="beliefs_teamwork_2",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Strongly Disagree"),
                    (2, "Disagree"),
                    (3, "Neither Agree nor Disagree"),
                    (4, "Agree"),
                    (5, "Strongly Agree"),
                    (9, "Don't Know"),
                ],
                default=None,
                null=True,
                verbose_name="It is easy is it for me to talk about data with others across my organisation.",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="confirmation_message",
            field=models.TextField(
                blank=True,
                help_text="This is a closing paragraph shown to respondents after they have completed their survey.",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="include_data_used_or_created",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Show question on data used and created by the respondent"),
                    (2, "Hide question on data used and created by the respondent"),
                ],
                default=2,
                help_text="If selected, we will ask additional questions for each of the 'I-D-E-A-L' behaviours that can be downloaded and analysed.",
                verbose_name="Ask respondents about data they use",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="preamble",
            field=models.TextField(
                blank=True,
                help_text="This is a closing paragraph that is shown to respondents at the start of the assessment survey.",
                verbose_name="Introductory text",
            ),
        ),
    ]
