# Generated by Django 5.2.12 on 2026-03-20 01:10

import django.db.models.deletion
import shortuuid.main
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast_toolkit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='use_custom_industries',
            field=models.BooleanField(default=False, help_text='If enabled, respondents will choose from your custom industry list instead of the default ISIC categories.', verbose_name='Use custom industry list'),
        ),
        migrations.AlterField(
            model_name='response',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='industry',
            field=models.CharField(blank=True, choices=[('I', 'Accommodation and food service activities'), ('N', 'Administrative and support service activities'), ('A', 'Agriculture, forestry and fishing'), ('R', 'Arts, entertainment and recreation'), ('F', 'Construction'), ('P', 'Education'), ('D', 'Electricity, gas, steam and air conditioning supply'), ('K', 'Financial and insurance activities'), ('Q', 'Human health and social work activities'), ('J', 'Information and communication'), ('C', 'Manufacturing'), ('L', 'Real estate activities'), ('B', 'Mining and quarrying'), ('M', 'Professional, scientific and technical activities'), ('O', 'Public administration and defence; compulsory social security'), ('H', 'Transportation and storage'), ('E', 'Water supply; sewerage, waste management and remediation activities'), ('G', 'Wholesale and retail trade; repair of motor vehicles and motorcycles'), ('S', 'Other service activities')], max_length=256, null=True, verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='share_link',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256),
        ),
        migrations.CreateModel(
            name='CustomIndustry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_industries', to='mast_toolkit.survey')),
            ],
            options={
                'verbose_name_plural': 'custom industries',
            },
        ),
    ]
