# Generated by Django 5.1.4 on 2026-03-23 21:51

import django.db.models.deletion
import shortuuid.main
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mast_toolkit", "0002_response_industry_response_is_complete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="self_assess_secure",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Strongly Disagree"),
                    (2, "Disagree"),
                    (3, "Neither Agree nor Disagree"),
                    (4, "Agree"),
                    (5, "Strongly Agree"),
                    (9, "Don't Know"),
                ],
                default=None,
                help_text="Security includes things like protection against unauthorised access, loss, or damage.",
                null=True,
                verbose_name="Data at my organisation is generally secure.",
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="self_assess_trust",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Strongly Disagree"),
                    (2, "Disagree"),
                    (3, "Neither Agree nor Disagree"),
                    (4, "Agree"),
                    (5, "Strongly Agree"),
                    (9, "Don't Know"),
                ],
                default=None,
                help_text="Trust includes things like confidence in data quality, or confidence that data is used ethically and in line with regulations.",
                null=True,
                verbose_name="Data at my organisation is generally trusted.",
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="self_assess_value",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Strongly Disagree"),
                    (2, "Disagree"),
                    (3, "Neither Agree nor Disagree"),
                    (4, "Agree"),
                    (5, "Strongly Agree"),
                    (9, "Don't Know"),
                ],
                default=None,
                help_text="Value includes things like improving decision making, improving services, or meeting regulatory requirements.",
                null=True,
                verbose_name="My organisation gets the best value it can from our data",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="use_custom_industries",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, respondents will choose from your custom industry list instead of the default ISIC categories.",
                verbose_name="Use custom industry list",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=256,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="industry",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Industry"
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="tools",
            field=models.TextField(
                blank=True,
                verbose_name="(Optional) What tools do you use to document and organise data at your organisation?",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="benchmark_scope",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Single organisation survey"),
                    (2, "Multi-organisation/industry-wide survey"),
                ],
                default=1,
                help_text="If you are doing a survey of people in your organisation, select 'Single Organisation'. If you are running for a survey across multiple organisations such as for an industry benchmark, select 'Multi-organisation industry-wide survey'.",
                verbose_name="Survey type",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=256,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="share_link",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256
            ),
        ),
        migrations.CreateModel(
            name="CustomIndustry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_industries",
                        to="mast_toolkit.survey",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "custom industries",
            },
        ),
    ]
