# Generated by Django 5.2.12 on 2026-03-20 05:02

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast_toolkit', '0003_alter_response_id_alter_response_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='self_assess_secure',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name="How secure do you believe your organisation's data to be?"),
        ),
        migrations.AddField(
            model_name='response',
            name='self_assess_trust',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='How much do you trust the accuracy of your data?'),
        ),
        migrations.AddField(
            model_name='response',
            name='self_assess_value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='How valuable is data to your role?'),
        ),
        migrations.AlterField(
            model_name='response',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='share_link',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256),
        ),
    ]
