# Generated by Django 5.2.12 on 2026-03-13 05:32

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast_toolkit', '0003_alter_response_id_alter_survey_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='industry',
            field=models.CharField(blank=True, choices=[('I', 'Accommodation and food service activities'), ('N', 'Administrative and support service activities'), ('A', 'Agriculture, forestry and fishing'), ('R', 'Arts, entertainment and recreation'), ('F', 'Construction'), ('P', 'Education'), ('D', 'Electricity, gas, steam and air conditioning supply'), ('K', 'Financial and insurance activities'), ('Q', 'Human health and social work activities'), ('J', 'Information and communication'), ('C', 'Manufacturing'), ('L', 'Real estate activities'), ('B', 'Mining and quarrying'), ('M', 'Professional, scientific and technical activities'), ('O', 'Public administration and defence; compulsory social security'), ('H', 'Transportation and storage'), ('E', 'Water supply; sewerage, waste management and remediation activities'), ('G', 'Wholesale and retail trade; repair of motor vehicles and motorcycles'), ('S', 'Other service activities')], max_length=1, null=True, verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='response',
            name='seniority',
            field=models.CharField(blank=True, choices=[('C', 'CXO'), ('S', 'Senior'), ('M', 'Mid-Level'), ('J', 'Junior')], max_length=1, null=True, verbose_name='Seniority level'),
        ),
        migrations.AddField(
            model_name='response',
            name='tools',
            field=models.TextField(blank=True, verbose_name='What tools do you use to work with data?'),
        ),
        migrations.AlterField(
            model_name='response',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='share_link',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256),
        ),
    ]
