# Generated by Django 5.2.12 on 2026-03-26 23:34

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast_toolkit', '0003_response_self_assess_secure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='self_assess_secure',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name="How secure do you believe your organisation's data to be?"),
        ),
        migrations.AlterField(
            model_name='response',
            name='self_assess_trust',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='How much do you trust the accuracy of your data?'),
        ),
        migrations.AlterField(
            model_name='response',
            name='self_assess_value',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='How valuable is data to your role?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='benchmark_scope',
            field=models.PositiveIntegerField(choices=[(1, 'Organisation-Only'), (2, 'Industry-Wide')], default=1, help_text='Select whether to compare results within your organisation only or across the industry.', verbose_name='Survey type'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='share_link',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256),
        ),
    ]
