# Generated by Django 5.2.12 on 2026-03-15 23:09

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast_toolkit', '0004_response_industry_response_seniority_response_tools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='other_tool',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='response',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='seniority',
            field=models.CharField(blank=True, choices=[('C', 'CXO / Executive (15+ years)'), ('S', 'Senior (8–15 years)'), ('M', 'Mid-Level (3–7 years)'), ('J', 'Junior (0–2 years)')], max_length=1, null=True, verbose_name='Seniority level'),
        ),
        migrations.AlterField(
            model_name='response',
            name='tools',
            field=models.CharField(blank=True, choices=[('SP', 'SharePoint'), ('CO', 'Collibra'), ('PV', 'Microsoft Purview'), ('AR', 'Aristotle Metadata'), ('IN', 'Informatica'), ('DG', 'Data.gov.au'), ('OT', 'Other tools (please provide more details below)')], max_length=2, null=True, verbose_name='What tools do you use to work with data in the organisation?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='benchmark_scope',
            field=models.PositiveIntegerField(choices=[(1, 'Organisation-Only'), (2, 'Industry-Wide')], default=1, help_text='Select whether to compare results within your organisation only or across the industry.', verbose_name='Survey type'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='share_link',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256),
        ),
    ]
