# Generated by Django 5.2.12 on 2026-03-16 03:53

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mast_toolkit', '0007_response_is_complete_alter_response_actions_audit_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='tools',
            field=models.TextField(blank=True, verbose_name='What tools do you use to document and organise data at your organisation?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='share_link',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=256),
        ),
    ]
